name: linteo
description: Flutter and Dart lint rules used at iteo
version: 1.3.0

repository: https://github.com/Iteo/linteo
issue_tracker: https://github.com/Iteo/linteo/issues
homepage: https://github.com/Iteo/linteo
documentation: https://github.com/Iteo/linteo

environment:
  sdk: ">=3.1.0 <4.0.0"
